version: 2.1

dev: &dev
  filters:
    branches:
      ignore: develop
  context: dev

staging: &staging
  filters:
    branches:
      only: develop
  context: staging

prod: &prod
  filters:
    tags:
      only: /^\d+\.\d+\.\d+$/
    branches:
      ignore: /.*/
  context: prod

not_scheduled: &not_scheduled
  when:
    not:
      equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]

nightly: &nightly
  when:
    and:
      - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
      - equal: [ nightly_build, << pipeline.schedule.name >> ]

orbs:
  aws-cli: circleci/aws-cli@3.1.3
  aws-ecr: circleci/aws-ecr@8.2.1
  github-cli: circleci/github-cli@2.2.0
  devops: terawatt-infrastructure/devops-orb@3.1.8

jobs:
  build-image:
    parameters:
      image_repo:
        type: string
      dockerfile_path:
        type: string
        default: "Dockerfile"
      build_args:
        type: string
        default: ""
      build_path:
        type: string
        default: "."
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run: |
          ./gradlew buildNeeded
          ./gradlew buildBackend
          mkdir -p tools/docker/openems-backend/build
          mv build/openems-backend.jar tools/docker/openems-backend/build
      - devops/build-image:
          build_args: "<< parameters.build_args >>"
          dockerfile_path: << parameters.dockerfile_path >>
          image_repo: << parameters.image_repo >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          build_path: << parameters.build_path >>

  deploy:
    parameters:
      environment:
        type: enum
        default: development
        enum:
          - development
          - staging
          - production
      image_repo:
        type: string
      application:
        type: string
      tag_values_path:
        type: string
    description: "Deploys App to Environment"
    docker:
      - image: cimg/base:stable
    steps:
      - devops/gitops-deploy:
          application: "<< parameters.application >>"
          image_repo: "<< parameters.image_repo >>"
          environment: << parameters.environment >>
          tag_values_path: "<< parameters.tag_values_path >>"
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>

workflows:
  dev:
    <<: *not_scheduled
    jobs:
      - build-image:
          <<: *dev
          name: build-image-backend
          image_repo: ems-backend
          dockerfile_path: tools/docker/openems-backend/Dockerfile
          build_path: tools/docker/openems-backend
      - deploy:
          requires:
            - build-image-backend
          <<: *dev
          name: deploy-backend
          application: openems
          tag_values_path: .backend.image.tag
          image_repo: openems
          environment: development
      - build-image:
          <<: *dev
          name: build-image-frontend
          image_repo: ems-ui
          dockerfile_path: tools/docker/openems-ui/Dockerfile
      - deploy:
          requires:
            - build-image-frontend
          <<: *dev
          name: deploy-frontend
          application: openems
          tag_values_path: .ui.image.tag
          image_repo: openems
          environment: development
  staging:
    <<: *not_scheduled
    jobs:
      - build-image:
          <<: *staging
          name: build-image-backend
          image_repo: ems-backend
          dockerfile_path: tools/docker/openems-backend/Dockerfile
          build_path: tools/docker/openems-backend
      - deploy:
          requires:
            - build-image-backend
          <<: *staging
          name: deploy-backend
          application: openems
          tag_values_path: .backend.image.tag
          image_repo: openems
          environment: staging
      - build-image:
          <<: *staging
          name: build-image-frontend
          image_repo: ems-ui
          dockerfile_path: tools/docker/openems-ui/Dockerfile
      - deploy:
          requires:
            - build-image-frontend
          <<: *staging
          name: deploy-frontend
          application: openems
          tag_values_path: .ui.image.tag
          image_repo: openems
          environment: staging
