<<<<<<<< Updated upstream:io.openems.edge.meter.accuenergy.acuview_2100/src/io/openems/edge/meter/accuenergy/acuview_2100/Config.java
package io.openems.edge.meter.accuenergy.acuview_2100;
========
package io.openems.edge.meter.accuenergy.acuRev2100;
>>>>>>>> Stashed changes:io.openems.edge.meter.accuenergy.acurev2100/src/io/openems/edge/meter/accuenergy/acuRev2100/Config.java

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.meter.api.MeterType;

@ObjectClassDefinition(//
<<<<<<<< Updated upstream:io.openems.edge.meter.accuenergy.acuview_2100/src/io/openems/edge/meter/accuenergy/acuview_2100/Config.java
		name = "Accuenergy Acuview 2100 Meter", //
		description = "Implements Accuenergy Acuview 2100 Meter")
========
		name = "Accuenergy AcuRev 2100", //
		description = "Accuenergy AcuRev 2100")
>>>>>>>> Stashed changes:io.openems.edge.meter.accuenergy.acurev2100/src/io/openems/edge/meter/accuenergy/acuRev2100/Config.java
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "io.openems.edge.meter.accuenergy.acuview_21000";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";
	
	@AttributeDefinition(name = "Meter-Type", description = "Grid(=default), Production, Consumption")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

<<<<<<<< Updated upstream:io.openems.edge.meter.accuenergy.acuview_2100/src/io/openems/edge/meter/accuenergy/acuview_2100/Config.java
	String webconsole_configurationFactory_nameHint() default "Accuenergy Acuview 2100 Meter [{id}]";
========
	String webconsole_configurationFactory_nameHint() default "Accuenergy AcuRev 2100 [{id}]";
>>>>>>>> Stashed changes:io.openems.edge.meter.accuenergy.acurev2100/src/io/openems/edge/meter/accuenergy/acuRev2100/Config.java

}